#!/usr/bin/env python3
"""同步项目级 Skill 入口，并安全审计旧的用户级同名副本。"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Mapping, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
HOST_SKILL_ROOTS = (
    Path(".agents") / "skills",
    Path(".claude") / "skills",
)
MANAGED_MARKER = "<!-- Generated by scripts/sync_project_skills.py; DO NOT EDIT. -->"
ARCHIVE_SCHEMA = "chinese-research-latex-project-skills-archive-v1"
SKILL_NAME_PATTERN = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
HOST_FRONTMATTER_KEYS = {"allowed-tools", "description", "license", "metadata", "name"}


class SkillConfigError(ValueError):
    """Skill 源目录或生成入口不满足项目契约。"""


class ArchiveSafetyError(ValueError):
    """全局 Skill 归档或恢复目标未通过路径安全检查。"""


@dataclass(frozen=True)
class SourceSkill:
    name: str
    directory: Path
    skill_md: Path
    frontmatter: str
    version: str | None


@dataclass(frozen=True)
class GlobalSkillCollision:
    host: str
    name: str
    path: Path
    kind: str
    project_version: str | None
    global_version: str | None


def _strip_yaml_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _extract_frontmatter(text: str, source: Path) -> str:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise SkillConfigError(f"SKILL.md 缺少 YAML frontmatter: {source}")
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "".join(lines[: index + 1]).rstrip("\r\n")
    raise SkillConfigError(f"SKILL.md 的 YAML frontmatter 未闭合: {source}")


def _frontmatter_value(frontmatter: str, key_name: str, source: Path) -> str:
    for line in frontmatter.splitlines()[1:-1]:
        if line.startswith((" ", "\t")) or ":" not in line:
            continue
        key, value = line.split(":", 1)
        if key.strip() == key_name:
            result = _strip_yaml_scalar(value)
            if result:
                return result
    raise SkillConfigError(f"SKILL.md frontmatter 缺少顶层 {key_name}: {source}")


def _host_frontmatter(frontmatter: str) -> str:
    output = ["---"]
    keep_block = False
    for line in frontmatter.splitlines()[1:-1]:
        if line and not line.startswith((" ", "\t")) and ":" in line:
            key = line.split(":", 1)[0].strip()
            keep_block = key in HOST_FRONTMATTER_KEYS
        if keep_block:
            output.append(line)
    output.append("---")
    return "\n".join(output)


def _config_identity(config_path: Path) -> tuple[str, str | None]:
    if not config_path.is_file():
        raise SkillConfigError(f"Skill 缺少 config.yaml: {config_path.parent}")
    in_skill_info = False
    name: str | None = None
    version: str | None = None
    for raw_line in config_path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not raw_line.startswith((" ", "\t")):
            if stripped == "skill_info:":
                in_skill_info = True
                continue
            if in_skill_info:
                break
        if not in_skill_info or ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        if key == "name":
            name = _strip_yaml_scalar(value)
        elif key == "version":
            version = _strip_yaml_scalar(value)
    if not name:
        raise SkillConfigError(f"config.yaml 缺少 skill_info.name: {config_path}")
    return name, version


def _read_optional_version(skill_dir: Path) -> str | None:
    config_path = skill_dir / "config.yaml"
    if not config_path.is_file():
        return None
    try:
        _, version = _config_identity(config_path)
    except SkillConfigError:
        return None
    return version


def discover_source_skills(project_root: Path = REPO_ROOT) -> dict[str, SourceSkill]:
    """发现并校验 ``skills/*`` 中的项目自有 Skill。"""
    project_root = project_root.expanduser().absolute()
    source_root = project_root / "skills"
    if not source_root.is_dir():
        raise SkillConfigError(f"找不到项目 Skill 源目录: {source_root}")

    result: dict[str, SourceSkill] = {}
    for skill_md in sorted(source_root.glob("*/SKILL.md")):
        directory = skill_md.parent
        directory_name = directory.name
        if len(directory_name) > 64 or not SKILL_NAME_PATTERN.fullmatch(directory_name):
            raise SkillConfigError(
                "Skill 目录名必须是最多 64 个字符的 lowercase 字母、数字和连字符组合: "
                f"{directory}"
            )
        text = skill_md.read_text(encoding="utf-8")
        frontmatter = _extract_frontmatter(text, skill_md)
        declared_name = _frontmatter_value(frontmatter, "name", skill_md)
        _frontmatter_value(frontmatter, "description", skill_md)
        if declared_name != directory_name:
            raise SkillConfigError(
                f"Skill 目录名与 SKILL.md name 不一致: {directory_name} != {declared_name} ({skill_md})"
            )
        config_path = directory / "config.yaml"
        version: str | None = None
        if config_path.is_file():
            configured_name, version = _config_identity(config_path)
            if configured_name != directory_name:
                raise SkillConfigError(
                    f"Skill 目录名与 config.yaml skill_info.name 不一致: "
                    f"{directory_name} != {configured_name} ({config_path})"
                )
        result[directory_name] = SourceSkill(
            name=directory_name,
            directory=directory,
            skill_md=skill_md,
            frontmatter=frontmatter,
            version=version,
        )
    if not result:
        raise SkillConfigError(f"未在 {source_root} 下发现任何 SKILL.md")
    return result


def build_entrypoint(skill: SourceSkill, target: Path) -> str:
    """为宿主官方发现目录生成只引用唯一源码的薄入口。"""
    relative_source = Path(os.path.relpath(skill.skill_md, start=target.parent)).as_posix()
    return (
        f"{_host_frontmatter(skill.frontmatter)}\n\n"
        f"{MANAGED_MARKER}\n\n"
        "# Project-local Skill entrypoint\n\n"
        "This file only exposes the repository-owned Skill to the current host. "
        "Before taking any task action, read the canonical instructions below completely:\n\n"
        f"- [`{relative_source}`]({relative_source})\n\n"
        "Treat that canonical `SKILL.md` as the sole execution source of truth. "
        "Resolve every relative script, reference, asset, and template path against the "
        "directory containing the canonical file. Do not edit this generated entrypoint.\n"
    )


def _path_exists(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def _ensure_safe_host_root(project_root: Path, host_root: Path) -> None:
    current = project_root
    for component in host_root.relative_to(project_root).parts:
        current /= component
        if current.is_symlink():
            raise SkillConfigError(f"拒绝经符号链接写入项目 Skill 根目录: {current}")


def _ensure_entrypoint(target: Path, expected: str, *, check_only: bool) -> str:
    if target.parent.is_symlink() or target.is_symlink():
        raise SkillConfigError(f"拒绝覆盖符号链接形式的项目 Skill 入口: {target}")
    current = target.read_text(encoding="utf-8") if target.is_file() else None
    if current == expected:
        return f"OK {target}"
    if check_only:
        return f"MISMATCH {target}"
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.tmp-{os.getpid()}")
    temporary.write_text(expected, encoding="utf-8")
    os.replace(temporary, target)
    return f"UPDATED {target}"


def _stale_managed_entrypoints(host_root: Path, expected_names: set[str]) -> list[Path]:
    if not host_root.is_dir() or host_root.is_symlink():
        return []
    stale: list[Path] = []
    for child in sorted(host_root.iterdir()):
        if child.name in expected_names or child.is_symlink() or not child.is_dir():
            continue
        skill_md = child / "SKILL.md"
        if skill_md.is_file() and not skill_md.is_symlink():
            content = skill_md.read_text(encoding="utf-8")
            if MANAGED_MARKER in content:
                stale.append(skill_md)
    return stale


def sync_project_skills(project_root: Path = REPO_ROOT, *, check_only: bool) -> list[str]:
    """同步或只读校验 Codex/Claude Code 的项目级 Skill 薄入口。"""
    project_root = project_root.expanduser().absolute()
    skills = discover_source_skills(project_root)
    expected_names = set(skills)
    messages: list[str] = []

    for relative_host_root in HOST_SKILL_ROOTS:
        host_root = project_root / relative_host_root
        _ensure_safe_host_root(project_root, host_root)
        for skill in skills.values():
            target = host_root / skill.name / "SKILL.md"
            expected = build_entrypoint(skill, target)
            messages.append(_ensure_entrypoint(target, expected, check_only=check_only))

        for stale in _stale_managed_entrypoints(host_root, expected_names):
            if check_only:
                messages.append(f"MISMATCH stale managed entrypoint {stale}")
                continue
            stale.unlink()
            try:
                stale.parent.rmdir()
            except OSError:
                pass
            messages.append(f"REMOVED {stale}")
    return messages


def has_mismatch(messages: Sequence[str]) -> bool:
    return any(message.startswith("MISMATCH ") for message in messages)


def default_global_roots() -> dict[str, Path]:
    home = Path.home()
    return {
        "agents": home / ".agents" / "skills",
        "claude": home / ".claude" / "skills",
        "legacy-codex": home / ".codex" / "skills",
    }


def audit_global_skills(
    project_root: Path = REPO_ROOT,
    roots: Mapping[str, Path] | None = None,
) -> list[GlobalSkillCollision]:
    """只读查找用户级目录中与本项目同名的 Skill。"""
    skills = discover_source_skills(project_root)
    selected_roots = roots or default_global_roots()
    collisions: list[GlobalSkillCollision] = []
    for host, root in selected_roots.items():
        root = root.expanduser().absolute()
        for skill in skills.values():
            candidate = root / skill.name
            if not _path_exists(candidate):
                continue
            kind = "symlink" if candidate.is_symlink() else "directory" if candidate.is_dir() else "file"
            collisions.append(
                GlobalSkillCollision(
                    host=host,
                    name=skill.name,
                    path=candidate,
                    kind=kind,
                    project_version=skill.version,
                    global_version=_read_optional_version(candidate) if candidate.is_dir() else None,
                )
            )
    return sorted(collisions, key=lambda item: (item.host, item.name))


def _validate_component(value: str, label: str) -> None:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", value):
        raise ArchiveSafetyError(f"非法的 {label}: {value!r}")


def _write_json_atomic(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def _assert_exact_global_target(path: Path, host: str, name: str, roots: Mapping[str, Path]) -> None:
    if host not in roots:
        raise ArchiveSafetyError(f"manifest 使用了未批准的全局根目录标签: {host}")
    _validate_component(name, "Skill 名称")
    expected = roots[host].expanduser().absolute() / name
    if path.expanduser().absolute() != expected:
        raise ArchiveSafetyError(f"目标不在 approved global root 的精确 Skill 路径下: {path}")


def archive_global_skills(
    project_root: Path = REPO_ROOT,
    roots: Mapping[str, Path] | None = None,
    *,
    backup_root: Path | None = None,
    archive_id: str | None = None,
) -> Path | None:
    """把精确匹配的项目自有全局副本移动到可恢复归档。"""
    selected_roots = dict(roots or default_global_roots())
    collisions = audit_global_skills(project_root, selected_roots)
    if not collisions:
        return None

    for collision in collisions:
        if collision.kind not in {"directory", "symlink"}:
            raise ArchiveSafetyError(
                f"全局 Skill 冲突必须是目录或符号链接，拒绝移动普通文件: {collision.path}"
            )
        _validate_component(collision.host, "宿主标签")
        _assert_exact_global_target(collision.path, collision.host, collision.name, selected_roots)

    archive_id = archive_id or dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    _validate_component(archive_id, "归档 ID")
    backup_root = (backup_root or (Path.home() / ".ChineseResearchLaTeX" / "skill-backups"))
    archive_dir = backup_root.expanduser().absolute() / archive_id
    if _path_exists(archive_dir):
        raise ArchiveSafetyError(f"归档目录已存在，拒绝覆盖: {archive_dir}")
    manifest_path = archive_dir / "manifest.json"
    payload: dict = {
        "schema": ARCHIVE_SCHEMA,
        "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "project_root": str(project_root.expanduser().absolute()),
        "project_owned_names": sorted(discover_source_skills(project_root)),
        "entries": [],
    }
    _write_json_atomic(manifest_path, payload)

    for collision in collisions:
        destination = archive_dir / collision.host / collision.name
        if _path_exists(destination):
            raise ArchiveSafetyError(f"归档目标已存在，拒绝覆盖: {destination}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(collision.path), str(destination))
        payload["entries"].append(
            {
                "host": collision.host,
                "name": collision.name,
                "original": str(collision.path),
                "archived": str(destination),
            }
        )
        _write_json_atomic(manifest_path, payload)
    return manifest_path


def restore_global_skills(
    manifest_path: Path,
    roots: Mapping[str, Path] | None = None,
    *,
    owned_names: set[str],
) -> list[Path]:
    """按受信 manifest 恢复先前归档的用户级 Skill。"""
    manifest_path = manifest_path.expanduser().absolute()
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ArchiveSafetyError(f"归档 manifest 顶层必须是对象: {manifest_path}")
    if payload.get("schema") != ARCHIVE_SCHEMA:
        raise ArchiveSafetyError(f"不支持的归档 manifest: {manifest_path}")
    entries = payload.get("entries", [])
    if not isinstance(entries, list):
        raise ArchiveSafetyError(f"归档 manifest 的 entries 必须是列表: {manifest_path}")
    selected_roots = dict(roots or default_global_roots())
    operations: list[tuple[Path, Path]] = []
    for raw_entry in entries:
        if not isinstance(raw_entry, dict):
            raise ArchiveSafetyError(f"归档 manifest 的 entries 项必须是对象: {raw_entry!r}")
        host = str(raw_entry.get("host", ""))
        name = str(raw_entry.get("name", ""))
        if name not in owned_names:
            raise ArchiveSafetyError(f"manifest 中的 Skill 不属于当前项目: {name}")
        original = Path(str(raw_entry.get("original", ""))).expanduser().absolute()
        archived = Path(str(raw_entry.get("archived", ""))).expanduser().absolute()
        _assert_exact_global_target(original, host, name, selected_roots)
        expected_archive = manifest_path.parent / host / name
        if archived != expected_archive.absolute():
            raise ArchiveSafetyError(f"归档源不在 manifest 管理目录中: {archived}")
        if not _path_exists(archived):
            raise ArchiveSafetyError(f"归档源不存在: {archived}")
        if _path_exists(original):
            raise ArchiveSafetyError(f"恢复目标已存在，拒绝覆盖: {original}")
        operations.append((archived, original))

    restored: list[Path] = []
    for archived, original in operations:
        original.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(archived), str(original))
        restored.append(original)
    payload["restored_at"] = dt.datetime.now(dt.timezone.utc).isoformat()
    _write_json_atomic(manifest_path, payload)
    return restored


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("sync", help="生成或更新双宿主项目级 Skill 入口")
    subparsers.add_parser("check", help="只读检查项目级 Skill 入口是否同步")

    audit = subparsers.add_parser("audit-global", help="只读审计用户级同名 Skill")
    audit.add_argument("--json", action="store_true", help="以 JSON 输出审计结果")

    archive = subparsers.add_parser("archive-global", help="归档用户级同名 Skill")
    archive.add_argument("--apply", action="store_true", required=True, help="确认执行可恢复归档")

    restore = subparsers.add_parser("restore-global", help="从 manifest 恢复用户级 Skill")
    restore.add_argument("--manifest", type=Path, required=True, help="归档 manifest.json 路径")
    restore.add_argument("--apply", action="store_true", required=True, help="确认执行恢复")
    return parser


def _print_sync(messages: Sequence[str]) -> None:
    for message in messages:
        print(message)
    ok = sum(message.startswith("OK ") for message in messages)
    updated = sum(message.startswith("UPDATED ") for message in messages)
    removed = sum(message.startswith("REMOVED ") for message in messages)
    mismatches = sum(message.startswith("MISMATCH ") for message in messages)
    print(f"summary: ok={ok} updated={updated} removed={removed} mismatches={mismatches}")


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command in {"sync", "check"}:
            messages = sync_project_skills(REPO_ROOT, check_only=args.command == "check")
            _print_sync(messages)
            return 1 if has_mismatch(messages) else 0
        if args.command == "audit-global":
            collisions = audit_global_skills(REPO_ROOT)
            if args.json:
                print(json.dumps([asdict(item) | {"path": str(item.path)} for item in collisions], ensure_ascii=False, indent=2))
            else:
                for item in collisions:
                    print(
                        f"CONFLICT host={item.host} name={item.name} path={item.path} "
                        f"kind={item.kind} project_version={item.project_version or '-'} "
                        f"global_version={item.global_version or '-'}"
                    )
                print(f"summary: conflicts={len(collisions)}")
            return 0
        if args.command == "archive-global":
            manifest = archive_global_skills(REPO_ROOT)
            print(f"archive manifest: {manifest}" if manifest else "没有发现需要归档的同名全局 Skill。")
            return 0
        if args.command == "restore-global":
            restored = restore_global_skills(
                args.manifest,
                owned_names=set(discover_source_skills(REPO_ROOT)),
            )
            for path in restored:
                print(f"RESTORED {path}")
            print(f"summary: restored={len(restored)}")
            return 0
    except (ArchiveSafetyError, OSError, SkillConfigError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
